### ISSUE TITLE
Beta 2.0.7 Can't Launch any Executable

### ISSUE THREAD

**Issue by Nofsdad** [TanninOne/modorganizer#1050]
Just switched to MO from NMM by doing a deep uninstall of both NMM and my game, reinstalling the game through STEAM and installing MO from here.  Everything was going fine, all the executables worked, had even added FO4Edit to the executables and got it to work OK.  

Installed a few mods and attempted to start the game with the F4SE executable in MO and it just sat there with the black cmd window open and nothing happening.  Terminated to start, closed and reopened MO and tried each of the executables that had, until a few minutes earlier been working flawlessly through MO and none of them would start.  Part of the time I'd click and the Cmd window would open but nothing would happen, at other times I'd get EM "**_failed to spawn "XXX.exe": failed to start process (The parameter is incorrect, [87])_**.  I've seen this mentioned on quite a few other sites also so it appears to be fairly common.

I've been working on this for about two hours now, have tried everything I've found here and at S.T.E.P and cannot get it to work.  I can launch the game normally through F4SE and the game launcher, I just can't launch any executable, including the game exes through MO.

**Comment by Nofsdad** [comment]
If it makes any difference, this is what the MO.cfg looks like after I try to start something:
[General]
selected_profile=Default
ask_for_nexuspw=true
gameName=Fallout 4
gamePath=D:\\Games\\steamapps\\common\\Fallout 4
first_start=false
group_state=0
window_geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x2\x85\0\0\0\x85\0\0\x6\x32\0\0\x3q\0\0\x2\x8d\0\0\0\xa4\0\0\x6*\0\0\x3i\0\0\0\0\0\0\0\0\a\x80)
window_split=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x3\xde\0\0\x2\xa8\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
log_split=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x2\x62\0\0\0\x64\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
browser_geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\0\0\0\0\0\0\0\0\x3\xef\0\0\x2\xed\0\0\0\0\0\0\0\0\0\0\x3\xef\0\0\x2\xed\0\0\0\0\0\0\0\0\a\x80)
filters_visible=false
selected_executable=5

[PluginPersistance]
Python%20Proxy\tryInit=false

[customExecutables]
1\title=F4SE
1\custom=false
1\toolbar=false
1\ownicon=false
2\title=Fallout 4
2\custom=false
2\toolbar=false
2\ownicon=false
3\title=Fallout Launcher
3\custom=false
3\toolbar=false
3\ownicon=false
size=5
4\title=LOOT
4\custom=false
4\toolbar=false
4\ownicon=false
5\title=FO4Edit
5\custom=true
5\toolbar=false
5\ownicon=false
5\binary=D:/Games/FO4Edit/FO4Edit.exe
5\arguments="--game=Fallout4"
5\workingDirectory=D:/Games/FO4Edit
5\steamAppID=

[recentDirectories]
size=2
1\name=editExecutableBinary
1\directory=D:/Games/FO4Edit
2\name=editExecutableDirectory
2\directory=D:/Games

[geometry]
modList=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\a\x1\0\0\0\0\0\0\0\0\0\0\0\bT\0\0\0\x3\0\0\0\x4\0\0\0\n\0\0\0\x2\0\0\0\n\0\0\0\x6\0\0\0\n\0\0\x2\x2\0\0\0\b\x1\x1\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\x14\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\b\0\0\0\xa3\0\0\0\x1\0\0\0\0\0\0\0P\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x83\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0V\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x36\0\0\0\x1\0\0\0\0\0\0\x3\xe8\x1)
espList="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x2\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1I\0\0\0\x4\x1\x1\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xa1\0\0\0\x1\0\0\0\0\0\0\0\x32\0\0\0\x1\0\0\0\0\0\0\0;\0\0\0\x1\0\0\0\0\0\0\0;\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0)"
dataTree=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1I\0\0\0\x2\x1\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\x90\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x2\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\xe5\0\0\0\x1\0\0\0\0\0\0\x3\xe8\x1)
downloadView=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1-\0\0\0\x3\x1\x1\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x3\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x65\0\0\0\x1\0\0\0\0\0\0\x3\xe8\x1)

[Settings]
language=en_US
log_level=0
compact_downloads=false
meta_downloads=false
use_prereleases=false
nexus_login=true
nexus_username=
nexus_password=
offline_mode=false
use_proxy=false
load_mechanism=0
nmm_version=0.61.13
hide_unchecked_plugins=false
force_enable_core_files=false
display_foreign=true

[Plugins]
Basic%20diagnosis%20plugin\check_conflict=true
Basic%20diagnosis%20plugin\check_errorlog=true
Basic%20diagnosis%20plugin\check_font=true
Basic%20diagnosis%20plugin\check_missingmasters=true
Basic%20diagnosis%20plugin\check_overwrite=true
Basic%20diagnosis%20plugin\ow_ignore_empty=false
Basic%20diagnosis%20plugin\ow_ignore_log=false
FNIS%20Checker\enabled=false
FNIS%20Checker\sensitive=false
Fomod%20Installer\enabled=true
Fomod%20Installer\prefer=true
Fomod%20Installer\see_disabled_mods=false
Fomod%20Installer\use_any_file=false
INI%20Editor\associated=true
INI%20Editor\external=false
Python%20Proxy\enabled=true
Python%20Proxy\python_dir=
Simple%20Installer\enabled=true
Simple%20Installer\silent=false

[pluginBlacklist]
size=0

**Comment by MuchMucho** [comment]
I currently dont have any problems running Fallout 4, but I recently did which lead me to delete and reinstall game.

Like you I've also had problems with modorganizer loading exe files, normally in my case it is due to my antivirus program blocking scriptextenders and other files which I've downloaded unless you want to rightclick every single file and remove blocking, you could try and deactivate your antivirus program, If you dont feel safe and is worried about having deactivated your antivirus program, just go offline after having updated mods.

To compare ini files here under you finde what my modorganizer.ini looks like, but what I've noticed is that you have selected_executable=5, where mine is 1 since Im no programmer nor familiar with what you have installed I cant say if this is the problem.

[General]
selected_profile=Default
ask_for_nexuspw=true
gameName=Fallout 4
gamePath=E:\\SteamLibrary\\steamapps\\common\\Fallout 4
first_start=false
group_state=0
window_geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\0\x64\0\0\x1\x10\0\0\x5M\0\0\x3\xf5\0\0\0m\0\0\x1\x36\0\0\x5\x44\0\0\x3\xec\0\0\0\0\0\0\0\0\a\x80)
window_split=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x3h\0\0\x1T\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
log_split=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x2\x62\0\0\0\x64\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
browser_geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\0\0\0\0\0\0\0\0\x3\xef\0\0\x2\xed\0\0\0\0\0\0\0\0\0\0\x3\xef\0\0\x2\xed\0\0\0\0\0\0\0\0\a\x80)
filters_visible=false
selected_executable=1
backup_install=false
mod_info_tabs=@ByteArray(\0\0\0\t\0\0\0\xe\0t\0\x61\0\x62\0T\0\x65\0x\0t\0\0\0\f\0t\0\x61\0\x62\0I\0n\0i\0\0\0\x12\0t\0\x61\0\x62\0I\0m\0\x61\0g\0\x65\0s\0\0\0\xe\0t\0\x61\0\x62\0\x45\0S\0P\0s\0\0\0\x18\0t\0\x61\0\x62\0\x43\0o\0n\0\x66\0l\0i\0\x63\0t\0s\0\0\0\x1a\0t\0\x61\0\x62\0\x43\0\x61\0t\0\x65\0g\0o\0r\0i\0\x65\0s\0\0\0\x10\0t\0\x61\0\x62\0N\0\x65\0x\0u\0s\0\0\0\x10\0t\0\x61\0\x62\0N\0o\0t\0\x65\0s\0\0\0\x10\0t\0\x61\0\x62\0\x46\0i\0l\0\x65\0s)

[PluginPersistance]
Python%20Proxy\tryInit=false

[recentDirectories]
size=2
1\name=editExecutableBinary
1\directory=E:/SteamLibrary/steamapps/common/Fallout 4
2\name=installMod
2\directory=

[geometry]
modList=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\a\x1\0\0\0\0\0\0\0\0\0\0\0\bT\0\0\0\x3\0\0\0\x4\0\0\0\n\0\0\0\x6\0\0\0\n\0\0\0\x2\0\0\0\n\0\0\x3Q\0\0\0\b\x1\x1\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\x14\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\b\0\0\x1\x62\0\0\0\x1\0\0\0\0\0\0\0P\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0G\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0?\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\x1\x19\0\0\0\x1\0\0\0\0\0\0\x3\xe8\x1)
espList=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x2\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\x34\0\0\0\x4\x1\x1\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0}\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\x8e\0\0\0\x1\0\0\0\0\0\0\0\x37\0\0\0\x1\0\0\0\0\0\0\0\x41\0\0\0\x1\0\0\0\0\0\0\0.\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0)
dataTree=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\x45\0\0\0\x2\x1\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\x90\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x2\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0\xc8\0\0\0\x1\0\0\0\0\0\0\x3\xe8\x1)
downloadView="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1,\0\0\0\x3\x1\x1\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x3\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\x3\xe8\x1)"

[Settings]
language=en_US
log_level=0
compact_downloads=true
meta_downloads=true
use_prereleases=false
nexus_login=true
offline_mode=false
use_proxy=false
load_mechanism=0
hide_unchecked_plugins=false
force_enable_core_files=true
display_foreign=true
base_directory=E:/SteamLibrary/steamapps/common/Fallout 4/modorganizer
nexus_username=
nexus_password="="
nmm_version=0.61.13

[Plugins]
Basic%20diagnosis%20plugin\check_conflict=true
Basic%20diagnosis%20plugin\check_errorlog=true
Basic%20diagnosis%20plugin\check_font=true
Basic%20diagnosis%20plugin\check_missingmasters=true
Basic%20diagnosis%20plugin\check_overwrite=true
Basic%20diagnosis%20plugin\ow_ignore_empty=false
Basic%20diagnosis%20plugin\ow_ignore_log=false
FNIS%20Checker\enabled=false
FNIS%20Checker\sensitive=false
Fomod%20Installer\enabled=true
Fomod%20Installer\prefer=true
Fomod%20Installer\see_disabled_mods=false
Fomod%20Installer\use_any_file=false
INI%20Editor\associated=true
INI%20Editor\external=false
Python%20Proxy\enabled=true
Python%20Proxy\python_dir=
Simple%20Installer\enabled=true
Simple%20Installer\silent=false

[pluginBlacklist]
size=0

[customExecutables]
1\title=F4SE
1\custom=false
1\toolbar=false
1\ownicon=false
2\title=Fallout 4
2\custom=false
2\toolbar=false
2\ownicon=false
3\title=Fallout Launcher
3\custom=false
3\toolbar=false
3\ownicon=false
4\title=LOOT
4\custom=false
4\toolbar=false
4\ownicon=false
size=4

[Servers]

[CompletedWindowTutorials]
InstallDialog=true

**Comment by Nofsdad** [comment]
I figured out what the problem was and it was a combination of me being new to MO and me being... well... stupid.  Everything is working OK.  I had simply forgotten to launch the game with its own launcher to set the ini files. Nine years of playing Fallout in one form or another and I forget something like that.  I chalk it up to being 74 years old, blame it on dementia. :D
