### ISSUE TITLE
Bug/Issue: Mod Organizer

### ISSUE THREAD

**Issue by FIRESKULL3939** [TanninOne/modorganizer#332]
I have a promblem were the mod organizer doesnt put the mods in the skyrim le folder and it just installs it to it own folder.

**Comment by ThosRTanner** [comment]
That is how Mod organizer works. It stores each mod separately (rather than jumbling them all together as NMM or manual installs do), and then when it runs skyrim it makes it look at the mod organiser directories for mods.

In order to do this it is necessary to start skyrim from mod organiser or skyrim won't see the mods. That is all explained on the nexus page.
