### ISSUE TITLE
Fallout 4 - Long Delay After "Press Any Button To Start"

### ISSUE THREAD

**Issue by Neovalen** [TanninOne/modorganizer#373]
When using Mod Organizer 2 with Fallout 4 there is a long pause (2-3 seconds) after pressing any button to bring up the main menu that is not present without Mod Organizer running. I did not notice any slowdown after this point however.

**Comment by Arthur-Neto** [comment]
I don't know why you opened a issue, since this isn't a issue, it's clearly the game loading the mods...

**Comment by Neovalen** [comment]
It doesn't happen using NMM so therefore is MO specific.

**Comment by NoShotz** [comment]
NMM doesnt use a virtual filesystem, and therefore, loads them faster

**Comment by strangerism** [comment]
I have noticed this as well, it's quite unusual as it didn't happen on older version of MO while running 250+ mods on Skyrim. 

I don't know, it could be normal with this version considered MO2 is running in 64bit. Anyway it is better to mention anything unusual than rather assume it's the norm. Tannin would know what to do surely.

**Comment by TanninOne** [comment]
How many mods do you have installed to cause this delay?
Could you send me the newest usvfs-*date*.log immediately after experiencing the delay?

Btw.: it's always good to report a potential problem (if it hasnt been reported yet) and let me decide if its actually a bug.

**Comment by anub1s22** [comment]
i've run in to the same, running about 20 mods (mods folder is about 3 gigs) skyrim's mo has a slowdown aswell but it happens before the game starts up (and it's mods folder is 50 gigs so it doesn't seem normal but Frankenstein'd engine so who knows)
[usvfs-2015-11-25_23-45-44.txt](https://github.com/TanninOne/modorganizer/files/44489/usvfs-2015-11-25_23-45-44.txt)

however i did some snooping in the logs and noticed a lot of errors with optimized vanilla textures and FAR - Faraway Area Reform (LOD) both are pretty large and have a large volume of files (pretty sure they make up the bulk of the 3gb mod folder), disabling both fixed the issue.

upon yet further snooping the errors in optimized vanilla textures are pretty harmless FAR is the culprit for me with it's legion of errors.

**Comment by strangerism** [comment]
I confirm as well the long delay is caused by FAR. 

this is one of the error reported

03:42:20.777 <%P:7120> [W] error reported listing files in E:\ModOrganizer2\mods\FAR - Faraway Area Reform (LOD)\Textures\Terrain\Commonwealth\Commonwealth.16.32.-16.dds: 80000002

same error is generated by Optimized Vanilla Textures that instead CDT at main menu

03:37:39.667 <%P:7664> [W] error reported listing files in E:\ModOrganizer2\mods\Optimized Vanilla Textures\textures\Vehicles\Automotive\VaultTecVan_PreWar01a_s.DDS: 80000002

I wonder if modders and the tools they have used to extract the vanilla asset is the cause behind this instability.

**Comment by strangerism** [comment]
Tested the mod which caused this before with alpha2

http://www.nexusmods.com/fallout4/mods/1355/?

no delay this time. working normally.

**Comment by Neovalen** [comment]
Alpha 2 has no delay. Thanks Tannin!
