### ISSUE TITLE
plugin files not being written to data folder

### ISSUE THREAD

**Issue by CTKnudsen** [TanninOne/modorganizer#420]
Installing mods, MO Alpha 2 looks like it is working fine.  Install dirs all seem to look ok.  But no .esps are actually being written to the data folder.  No sign of this in the program, plugin and data tabs all look like they should, so far as I can tell.  

It seems as though the mods are being installed to the Fallout 4/ModOrganizer2/mods folder, for some reason.

Any help would be appreciated, please keep up the good work, as MO is IMHO the best mod tool out there.

**Comment by rdunlap** [comment]
That is the whole reason for MO in the first place. :) 
when you start the game using MO it takes all the installed and selected mods and makes a virtual Data directory that the game uses instead of the one that the game created. NOTE: It takes the games Original Data directory first then installs the mods to it in proper order so that when it actually starts the game the game see's and uses all your mods. If you start the game without MO then you get no pretty mods. but you never trash your game installation.
Do this change the EXE beside of Run to Fallout Launcher and hit Run. when the launcher is open click the secret spot (right shoulder of power armor) to open the games mods manager and you will see all your esp/esm files listed and selected.

Robert

**Comment by TanninOne** [comment]
explained.

**Comment by CTKnudsen** [comment]
Ok, thanks!

So I tried this and two issues arose:

1.  MO was unable to launch FO Launcher.  Error "failed to spawn "Fallout$Launcher.exe": failed to start process (The operation completed successfully. [0])" is received.

2.  Fallout4.exe does start, but I am then unable to see any saved games.

Will attempt to track down in open issues...
