### ISSUE TITLE
[FO4] BodySlide not working with MO2

### ISSUE THREAD

**Issue by LawLeewer** [TanninOne/modorganizer#454]
BodySlide needs CBBE archives to work properly, but even though MO appears to load both CBBE and BS archives and shows them on the same folder in the Data tab, BodySlide doesn't recognize any body installed.     
Everything works fine if installed manually or through NMM.

![image](https://cloud.githubusercontent.com/assets/15914402/11995425/54214ee6-aa37-11e5-9a1e-613f98c76684.png)

**Comment by rdunlap** [comment]
Its a known issue in the alpha. until the next release at least only Fallout4.exe is seeing the VFS. BodySlide.exe needs to be able to see the data and it cant since it cant see the VFS

Robert

**Comment by ogrotten** [comment]
Just to be clear, there's 2 discreet problems here.

1) as @rdunlap said, the bodyslide.exe isn't seeing the vfs. Can confirm by merging all bodyslide installs into one line item in the mod list. 

2) saving from within bodyslide doesn't work. In skyrim, bodyslide would generally save to overwrite. But since the overwrite dir is still in dev, save doesn't work.

**Comment by rdunlap** [comment]
Sorry!
I should have mentioned the Overwrite as incomplete. I just hopped on quickly the other day and thought to let him know that he would not be able to use BodySlide with MO2 at least till the next release.

Robert
