### ISSUE TITLE
problems getting fnis working in modorganizer 1.3.11

### ISSUE THREAD

**Issue by patchling** [TanninOne/modorganizer#464]
a little copy and paste of the fnis display. first one is from running fnis in mo last night, second one is from using nmm this morning.

mo

FNIS Behavior V6.2   12/29/15 10:20:37 PM
Skyrim: 1.9.32.0 - C:\Steam\steamapps\common\Skyrim\ (Steam)

Skeleton(hkx) female: XPMS2HDT (115 bones)   male: Unknown (99 bones)
Patch: "GENDER Specific Animations" 
Patch: "SKELETON Arm Fix" 

Reading FNISBase V6.2 ...
Reading MomoAJ V?.? ...
Reading XPMSE V6.1  ( 0 furniture, 0 offset, 0 paired, 0 kill, 0 chair, 152 alternate animations) ...
Reading boundwoodchopping V?.?  ( 1 furniture, 0 offset, 0 paired, 0 kill, 0 chair, 0 alternate animations) ...
Reading mslVampiricThirst V?.? ...

All Anim Lists scanned. Generating Behavior Files ...
 16 GENDER modifications for Animations\male
 45 GENDER modifications for Animations\female

ERROR(2012): Could not generate: defaultfemale.hkx defaultmale.hkx weapequip.hkx staggerbehavior.hkx sprintbehavior.hkx shout_behavior.hkx mt_behavior.hkx magicmountedbehavior.hkx magicbehavior.hkx magic_readied_direction_behavior.hkx 1hm_locomotion.hkx 1hm_behavior.hkx 0_master.hkx 

nmm

FNIS Behavior V6.2   12/30/15 12:53:48 PM
Skyrim: 1.9.32.0 - C:\Steam\steamapps\common\Skyrim\ (Steam)

Skeleton(hkx) female: XPMS2HDT (115 bones)   male: XPMS2HDT (115 bones)
Patch: "GENDER Specific Animations" 
Patch: "SKELETON Arm Fix" 

Reading boundwoodchopping V?.?  ( 1 furniture, 0 offset, 0 paired, 0 kill, 0 chair, 0 alternate animations) ...
Reading FNISBase V6.2 ...
Reading FNISCreatureVersion V6.1 ...
Reading MomoAJ V?.? ...
Reading mslVampiricThirst V?.? ...
Reading XPMSE V6.1  ( 0 furniture, 0 offset, 0 paired, 0 kill, 0 chair, 152 alternate animations) ...

All Anim Lists scanned. Generating Behavior Files ...
 16 GENDER modifications for Animations\male
 45 GENDER modifications for Animations\female
mt_behavior usage: 2.8 %   ( 1 furniture, 0 offset, 0 chair, 0 alternate animations)
0_master usage: 4.9 %   ( 0 paired, 0 kill, 80 alternate animations)
Alternate Animation mods: 1 sets: 16 total groups: 24 added file slots: 156 alternate files: 152

Create Creature Behaviors ...

 209 animations for 6 mods successfully included (character)

i have copys of the GenerateFNIS_LogFile.txt files for both runs sitting aside. they are 1,185kb for nmm and 808kb for mo. if you want to see them let me know how i can get them to you, i think they are a little big for here. but if you want i can post them here, post them somewhere else etc.

edit: i used these resources to install fnis in mo
ghopher: https://www.youtube.com/watch?v=VpOuGN-yr6E&index=11&list=PLE7DlYarj-DcLS9LyjEqOJwFUQIIQewcK
gamer poets: https://www.youtube.com/watch?v=6MqZ-EPdBvk
s.t.e.p. guide: http://wiki.step-project.com/Guide:Mod_Organizer#Third_Party_Programs

**Comment by patchling** [comment]
come on peeps, i need the help. i don't want to go back to nmm, but some of the mods comming out that i want to try need fnis to work. first choice is to get fnis working in mo. second choice is to do without the mods that require fnis. if i go back to nmm i may as well start manually installing my mods, because if i have a problem i am just going to have to delete everything in the skyrim directory to make shure i get all of the stuff out that gets put in when i am using nmm. all i need to do with modorganizer is untic everything, makes it much easer to find a mod conflict.

**Comment by ThosRTanner** [comment]
You'd do better asking on the STEP forums I think.

**Comment by patchling** [comment]
i will go look there, thankyou for the suggestion.

**Comment by patchling** [comment]
my saga of asking for help on step. http://forum.step-project.com/topic/8524-q-a-using-fnis-with-mod-organizer/page-14 196, 199, 203, 204, 205, 206, 207, 208, 209, 210 and 211

from GrantSP "According to @fore, FNIS's creator, JIT errors such as the one you posted are indicative of a system error that even the OS or the .NET runtime is unaware of. Sadly his recommended method to fix this is a reinstall of your OS."

i am attaching the log in question. but the short version is:
System.IO.FileNotFoundException: Could not find file 'C:\Steam\steamapps\common\Skyrim\data\meshes\actors\character\behaviors\0_master.hkx'.

[fnis just in time debugger.txt](https://github.com/TanninOne/modorganizer/files/87962/fnis.just.in.time.debugger.txt)

if anybody can think of something other than reinstalling my os i would appreciate it, because i do not know how to reinstall my os from a disc. reinstalling from the image i got from my computer manufacturer will only give me the same situation, i think.

**Comment by TanninOne** [comment]
I somehow doubt this is a problem that requires an os reinstall. The error message is quite simple: fnis can't find the file "C:\Steam\steamapps\common\Skyrim\data\meshes\actors\character\behaviors\0_master.hkx".

Now remember: MO has to redirect such file accesses, and in debug mode it is rather verbose in what the application does with files and how MO affects it.
So, in MO configure logging mode "debug", then run fnis. Once it's done (and closed) open the newest ModOrganizer_<date>.log (or just ModOrganizer.log) in Notepad++.
In Notepad++ select Search->Mark. Check the checkbox "Bookmark line" and in "Find what" enter "0_master.hkx", then hit "Mark All".
This bookmarks all lines where MO did something relating to that file. Now select Search->Bookmark->Copy Bookmarked Lines. Then create a new, empty tab and paste to see only those lines, it shouldn't be many.

When I run fnis (which is working) I get:
> DEBUG (20:21:11.0387): remove mod file D:\Steam Games\SteamApps\common\skyrim\data\meshes\actors\character\behaviors\0_master.hkx
> INFO (20:21:11.0387): deleting D:\Steam > Games\SteamApps\common\skyrim\data\meshes\actors\character\behaviors\0_master.hkx -> D:\ModOrganizer_new\mods\Fores New Idles in Skyrim - FNIS 6\meshes\actors\character\behaviors\0_master.hkx
> DEBUG (20:21:11.0653): create process (w) null - ".\hkxcmd.exe" convert -v:WIN32 "temporary_logs\0_master.xml" "temporary_logs\0_master.hkx" (in D:\Steam Games\SteamApps\common\skyrim\data\tools\GenerateFNIS_for_Users) - hooking
> DEBUG (20:21:13.0312): add mod file D:\ModOrganizer_new\overwrite\\tools\GenerateFNIS_for_Users\temporary_logs\0_master.hkx (tools\GenerateFNIS_for_Users\temporary_logs\0_master.hkx)
> DEBUG (20:21:13.0789): using path from previous deletion: D:\ModOrganizer_new\mods\Fores New Idles in Skyrim - FNIS 6\meshes\actors\character\behaviors\0_master.hkx
> DEBUG (20:21:13.0790): remove mod file D:\Steam Games\SteamApps\common\skyrim\data\tools\GenerateFNIS_for_Users\temporary_logs\0_master.hkx
> DEBUG (20:21:13.0790): add mod file D:\ModOrganizer_new\mods\Fores New Idles in Skyrim - FNIS 6\meshes\actors\character\behaviors\0_master.hkx (meshes\actors\character\behaviors\0_master.hkx)
> DEBUG (20:21:13.0790): move (ex) D:\Steam Games\SteamApps\common\skyrim\data\tools\GenerateFNIS_for_Users\temporary_logs\0_master.hkx to D:\Steam Games\SteamApps\common\skyrim\data\meshes\actors\character\behaviors\0_master.hkx - 1 (183)

This may still look like gibberish but it's not actually that complicated:
1. "remove mod file" says the file gets removed from MOs virtual file system. Why? That's on the next line
2. "deleting ..." - this is the application (fnis) removing the file. MO prints two paths, the first is what fnis says it wants to delete, the second is the file that actually gets deleted in one of my mods
3. "create process" - fnis uses an external program called "hkxcmd.exe". MO notices and applies it's vfs to that process too.
4. "add mod file" - a new file gets created by fnis, MO adds it to its vfs.

Now the remaing lines belong together. fnis moves the temporary file from step 4 to where the file actually belongs (line "move (ex)").
The destination of the move is the file deleted in step 2. MO notices that and directs the file to that location (line "using path from previous deletion").
Since the temporary file disappears in the move, MO removes it from its vfs (line "remove mod file") and adds the file in its final destination to the vfs (line "add mod file")


And in your case something seems to go wrong and the process cancels. Maybe the file is write protected and fnis can't delete it in step 2. Or your mod directory is write protected and the file can't be created in step 4

**Comment by patchling** [comment]
i did not think this was a reinstall situation. i reinstalled and reran everything. i was unable to find what you were pointing at. would looking at the logs help? the most recent logs are in the .zip

i do not think your example look like gibberish, just something that can be used for tech support.

[mo generated logs fnis attempt.zip](https://github.com/TanninOne/modorganizer/files/88289/mo.generated.logs.fnis.attempt.zip)

**Comment by TheGreenDragon** [comment]
Looking at the log files you posted, the first thing I notice is the GenerateFNIS_LogFile shows an unknown skeleton for males. Are you positive you have installed the skeleton files correctly? Are they being overwritten by another mod?

**Comment by TanninOne** [comment]
Well, so now you're a little further. I told you the sequence of commands fnis does and from your log we can tell that in your case fnis does only the first step: deleting 0_master.hkx.
Immediately afterwards it causes an exception code e0434352 and then ends. You don't need to know what e0434352 means, you can google it.
You will find  (on every single hit of the first couple of hundred pages of search results) that this signals any CLR/.Net exception - which is the framework used by fnis.

Since this is so close to the end of the log and is the only exception found in mos log and your jit log did also report an exception (FileNotFoundException to be more specific) we can assume that's the same one.
The jit log has a backtrace to the exception, and from that we find that fnis was calling FileInfo.get_Length().
Even without being able to code you can deduce that this means fnis was querying the size of that file.
And thanks to MO's log you now know that it did so immediately after deleting that very file!

This is the extend of what I can tell you by looking at it from the MO side.

**Comment by patchling** [comment]
@TheGreenDragon 
i use xmpse by groovtama. every version i have tried gets this same result, currently xpmse 3.71. i use the fomod to install it, and leave it at the default options. sorting by priority i have the skeleton last in my left pane window, just above the overwrite file, so no overwrites. and i have always found it extremely odd that i get this situation when running mo, but not with nmm.

**Comment by TheGreenDragon** [comment]
Are you running MO as admin? Very odd that it works correctly in NMM but not MO. What version of MO are you running?

**Comment by patchling** [comment]
yes i am running mo as admin. and according to the title of the thread (and the top left corner of the mo window) i am running version 1.3.11

every other tool i run through mo does fine. bodyslide, asis, wyre bash, rectificator etc...

**Comment by TheGreenDragon** [comment]
Sorry for missing the version number in the post, just trying to think of reasons this would not be working for you. I'm sure you have reinstalled FNIS in MO several times by now as well. Wish I could help more, but I've got nothing at this point.

**Comment by patchling** [comment]
we (fore, mistakenmystic and myself) finally got fnis working for me in the mod organizer environment. the saga of asking for help on nexus is here http://forums.nexusmods.com/index.php?/topic/3733385-need-help-getting-fnis-to-work-in-mo/ it took grantsp/mistakenmystic, fore, tannin42/tanninone and a little help from thegreendragon here and it is finally working.

short version: problem is caused by my security software. 

a work around is to open spybot search and destroy, navigate start menu > settings > live protection > mode > and uncheck the "scan programs before they start" option. i can turn it back on after the run. i have no clue as to why this happens in the mo environment but not with nmm. as this is an issue caused, in part, by my security software i think this counts as a closed issue now.
