### ISSUE TITLE
MO2 Alpha 3 crash at start

### ISSUE THREAD

**Issue by CarlCorey** [TanninOne/modorganizer#528]
I tried Alpha 3 to see if it would work with FO4 for me but it crashes at the beginning. The first time it's run, it reports the directory creation and then crashes. On subsequent attempts it just crashes. The diagnostic dump is attached. According to the Windows Event viewer, it's an issue with gameFalloutNV.dll. I have both FNV and FO4 installed via Steam. FO3 is installed separately from disk.

Event viewer report:
`
Faulting application name: ModOrganizer.exe, version: 2.0.0.0, time stamp: 0x5692b5cc
Faulting module name: gameFalloutNV.dll, version: 0.0.0.0, time stamp: 0x565b1bf7
Exception code: 0xc0000005
Fault offset: 0x000000000000d5e0
Faulting process id: 0x2a78
Faulting application start time: 0x01d15ae53408e4b1
Faulting application path: E:\Tools\ModOrganizer2\ModOrganizer.exe
Faulting module path: E:\Tools\ModOrganizer2\plugins\gameFalloutNV.dll
Report Id: 7363de32-c6d8-11e5-bef7-dc85de9f8f2e
Faulting package full name: 
Faulting package-relative application ID: 

`

[ModOrganizer.exe.dmp.zip](https://github.com/TanninOne/modorganizer/files/110513/ModOrganizer.exe.dmp.zip)

**Comment by CarlCorey** [comment]
Update. I had forgotten that I have MO installed for FNV (I never play it) so it's probably a collision. I'll uninstall that version and try again.

**Comment by CarlCorey** [comment]
Update. I had forgotten that I have MO installed for FNV (I never play it) so it's probably a collision. I'll uninstall that version and try again.

**Comment by Sir1Twist** [comment]
Check to see if you have bsa_extractor.dll in the Mod Organizer directory. If so, then move it out of the hierarchy of the directories for Mod Organizer. That may fix the problem.

**Comment by Leer0x** [comment]
Here is THE fix if you are using the non-portable standard install:
Travel to YourDrive:\Users\UserName\AppData\Local\ModOrganizer\Fallout 4
(Replace YourDrive and UserName with whatever corresponds on YOUR computer.)
Delete the ModOrganizer.ini file
Start up Mod Organizer Alpha 2a3
It will crash, this is normal.
Go back to YourDrive:\Users\UserName\AppData\Local\ModOrganizer\Fallout 4
Open ModOrganizer.ini and edit the following:
Change gameName=FalloutNV to gameName=Fallout 4
Set gamePath= to wherever your Fallout 4 game is installed, remember, you will have to put TWO backslashes (\\\) in the PATH because Python cannot read a single backslash as it is a command where it ignores the next letter, that is why you put two, because then Python will read JUST ONE of the backslashes, ignoring the ignore command...if you don't get this, just put TWO \\\ !
Save ModOrganizer.ini
You're good to go.
For me I tried fixing again (Because my MO doesn't start anymore, don't know if this is a global thing or anything) and it worked fine. SO GO AHEAD!

**Comment by paulholl** [comment]
Just a quick comment to confirm that the fix by Leer0x works, and to give a copy/paste of the ini for the lazy

[General]
gameName=Fallout 4
gamePath=C:\\Program Files (x86)\\Steam\\steamapps\\common\\Fallout 4

**Comment by Leer0x** [comment]
@paulholl Make sure to have 2 backslashes (\\) and not one

[General]
gameName=Fallout 4
gamePath=C:\\\Program Files (x86)\\\Steam\\\steamapps\\\common\\\Fallout 4

**Comment by CarlCorey** [comment]
Yes, that worked just fine, thank you Leer0x. Python can't use forward slashes in Windows paths? With the exception of the command line, where the forward slash has a different meaning, Windows doesn't care which direction the slashes lean.

**Comment by TanninOne** [comment]
was resolved in alpha 4
