### ISSUE TITLE
error opening file for writing

### ISSUE THREAD

**Issue by enjennumber9** [TanninOne/modorganizer#530]
Can't install any version using installers. Every file gets me a a popup with the below message: 

Error opening file for writing: 
C:\Program Files (x86)\Mod Organizer\Mod Organizer.exe
Click Abort to stop the installation,
Retry to again, or
Ignore to skip this file.

**Comment by noc9109** [comment]
Correct me if I'm wrong:
what I'm assuming is you are trying to install a mod and MO2A3 gives you this error message,
here is 2 thing might help:

> Travel to YourDrive:\Users\UserName\AppData\Local\ModOrganizer\Fallout 4
(Replace YourDrive and UserName with whatever corresponds on YOUR computer.)
Delete the ModOrganizer.ini file
Start up Mod Organizer Alpha 2a3
It will crash, this is normal.
Go back to YourDrive:\Users\UserName\AppData\Local\ModOrganizer\Fallout 4
Open ModOrganizer.ini and edit the following:
Change gameName=FalloutNV to gameName=Fallout 4
Set gamePath= to wherever your Fallout 4 game is installed, remember, you will have to put TWO backslashes (\) in the PATH because Python cannot read a single backslash as it is a command where it ignores the next letter, that is why you put two, because then Python will read JUST ONE of the backslashes, ignoring the ignore command...if you don't get this, just put TWO \\ !
Save ModOrganizer.ini

I'm not sure will this solve the problem, but might worth a try
another thing is, manually install mods into MO2A3/mods folder
if the zip or 7z or whatever package has a "data" folder in ti, simply go create a folder under the MO2A3/mods, and extract what you need form the "data" folder, then restart MO, that should do it

I'm not a moder or dev, sorry can't help too much, hope it would work

**Comment by TheGreenDragon** [comment]
It sounds to me as if you are actually getting this issue when attempting to install ModOrganizer2. If this is the case, Again head to your Users folder as described by noc9109 and delete the ModOrganizer folder entirely. Then, either run the setup by right clicking the file and choosing Run as Admin or install to a non protected folder, such as C:\Games\ModOrganizer.

**Comment by enjennumber9** [comment]
Running as admin did the trick. thanks!!

Thanks,
Jennifer Wright

**Comment by TheGreenDragon** [comment]
Glad to help. If you decided to install to the default location i.e. C:\Program Files (x86) remember to set the program to always run as admin. To do so, right click on the executable and choose Properties. In the window that appears choose the Compatibility tab and, near the bottom, place a check mark in "Run this program as administrator".
