### ISSUE TITLE
Multiple things to note and how to reproduce.

### ISSUE THREAD

**Issue by Budroi** [TanninOne/modorganizer#538]
Sorry first of all. I am not really too proficient with computer programming or anything of the like so ultimately anything i mention here could be an already tracked issue. if so close this post or have me edit out any info already tracked.

1. MO crashes after installing mods. reproduce= install any mod.
When you restart MO the mod is listed as installed but some files end up missing or were not transferred properly so they end up broken.

2. running any executable permanently hooks the "usvfs_x64.dll".
this does not seem to cause any problems but that file remains loaded by windows after closing out the executable or MO entirely.
reproduce= run any executable (bodyslide for instance) then close it out and try to delete the above named file. you will get an error saying you can not delete because it is in used by "...". even using a separate program that allows you to kill any processes/file in use does not see it. I used "open file view".
I found this problem out when i began to downgrade to alpha 2 so i could install mods again.when overwriting the alpha 3 files with alpha 2 files i have to skip that file because its in use with no way to close it. The only way i have been able to close it is by restarting my computer entirely. To note: This again does not seem to cause any issues that i can see because alpha 2 and 3 both run whether the above file is from alpha 2 or 3.
It should be noted that most if not all of the currently functional portions of MO still work while this file is still running. i can play the game and run bodyslide/loot/FO4Edit without any problems aside from those listed above or below.

3. problem 2 happens with usvfs_x86.dll when i tried to run bodyslide/loot from alpha 2.
I know this doesn't pertain to alpha 3 but i thought i would mention it anyway.

4. programs like bodyslide can not build armors/clothing if the loose file is not already present in a MO installed mod. Reproduce= grab bodyslide files that replace vanilla clothing that you "DO NOT" have loose file for already. Then when you build bodyslide will crash or if you batch build you will get an error saying can not write because the folder doesn't exist and you get similar error if you manually create the folder but there is no .nif for the batch built bodyslide file to replace.

5. FO4Edit crashes upon closing. reproduce= run FO4edit and close it.

6. My instincts tell me this one relates more to problem 4 than as a separate problem. executables can not do anything that would deposit something into the overwrite folder. Reproduce= use FO4Edit to create a new mod. When you save it, it ends up in the fallout 4 data directory rather than in the overwrite folder. I believe this is why Bodyslide can not generate files that do not already have loose files, Bodyslide would have tossed them into the Overwrite folder but instead it tries to place them into the main data directory which seems to be locked closed when MO has visualization in place.

7. this deals with alpha 2 and 3. if you open the ini editor to change fallout4.ini to have these lines, "bInvalidateOlderFiles=1" and "sResourceDataDirsFinal=". When you close out the game "sResourceDataDirsFinal=" ends up having a bunch of file folders listed. it looks like this "sResourceDataDirsFinal=INTERFACE\,MATERIALS\,MESHES\,MUSIC\,PROGRAMS\,SOUND\,STRINGS\,TEXTURES\,VIDEO\"
and you have to re edit the INI between each play or the game hangs when loading because we are not supposed to have anything listed there. It is all together possible this is not an issue with alpha 3 as i have to sitch between 2 and 3 often depending on what i want to do. ie: play game with a locked MO (see problem 8)=alpha 2, install mod=alpha 2, run any other executable (FO4Edit, Bodyslide, LOOT)=Alpha 3 because they do not run or run or run properly on alpha 2. of those 3 only LOOT runs on alpha 2 but for some reason it con not see my installed mods, but that could be because the file in problem one permarunning.

8. Lastly this is not a issue because i have found no negative effect from it but it is another thing of note. when you run fallout 4 MO virtualizes the folder properly but MO does not stay locked while Fallout 4 is running. I do not for certain understand why fallout 4 runs without problem even when MO is not locked but if I had to assume its because the file from problem one deals directly with virtualization so even though MO is not locked the structure is still virtualized because the virtualization never unhooked.

I could not find any crash logs to attach to this post but i am enclosing a zip  archive that has my logs folders from both "app data" and the MO install directory.
[MO Logs Folders.zip](https://github.com/TanninOne/modorganizer/files/120013/MO.Logs.Folders.zip)

**Comment by Budroi** [comment]
sorry typo with problem 4 . it should read as....
4. programs like bodyslide can "not" build.
stupid how even proofreading multiple times before posting can still leave errors when the post is long. Sorry again.

**Comment by GSDFan** [comment]
I will try to answer some of these to the best of my knowledge. I will assume MO 2 alpha 3.

1.	See [MO 2.0.3a crashes on merging and replacing mods](https://github.com/TanninOne/modorganizer/issues/480) this may help
2.	Very well may be. Also if an application launched by MO crashes it may hold the usvfs_x64.dll in memory until terminated with task manager. When LOOT 64 crashes on me, I can’t open another instance until I have terminated the ones in task manager. I can reproduce this behavior when LOOT crashes, locks the usvfs_x64.dll.
3.	May be tied to item 2.
4.	The Alpha states “fixed various bugs in the vfs library. Support for 32 bit targets (unstable)”.
5.	Alpha build “Support for 32 bit targets (unstable)”.
6.	Not enough info on my part, but it is an Alpha build.
7.	MO by design adds these to the ini file.
8.	I only see this when I run F4SE and not with the game itself, Fallout4.exe, from MO. I do not run the game from the launcher within MO. 

My guess in the locking of the interface is to prevent us from making changes in the UI when another program is going to make some sort of change itself. I personally would like an option to select to close the UI on executable launch.
This may be a bug, but my guess is the script extender executable has terminated and MO closes the locked dialog.

Lastly
> I do not for certain understand why fallout 4 runs without problem even when MO is not locked but if I had to assume its because the file from problem one deals directly with virtualization so even though MO is not locked the structure is still virtualized because the virtualization never unhooked.

Congratulations, you understand how MO works. The UI you see is used to manipulate the files and folders that MO presents to the game. The heavy lifting is done by usvfs_x64.dll and  usvfs_x86.dll in the alphas and hook.dll in the stable 1.xx version of MO. There is an option to run the game without using the UI in the shortcut selector.

**Comment by TanninOne** [comment]
Please
a) check if your issue has already been posted before you create a new report.
b) create one report per issue, otherwise the report will become a mess if people start to reply to individual issues and it will be impossible for me to update the status of individual issues.
