### ISSUE TITLE
 An error comes up and saying that the application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail. 

### ISSUE THREAD

**Issue by jonny420** [TanninOne/modorganizer#565]
How would i fix this problem? Thanks

**Comment by TanninOne** [comment]
a) the error message contains instructions
b) google has tons of information about this error
c) in short: required dlls are missing

Only a couple of hours ago you created an issue where you said MO used to work and then the MO exe got deleted. Now you create one that indicates further MO dlls are missing, I think there is a pattern...

**Comment by Goliatron** [comment]
I have the same issue.  I have reinstalled all redistributables, checked the 'winners' registry entry, tried this, tried that, still get the same error on load.

Since the auto-download function fails for some/many, it would be very helpful to know where the individual downloads need to go in the MO folder.  Do the QT DLLs go in the DLL folder, for example.

it would be wonderful if you had a complete download available with everything where it needs to be.

I would really like to help you get MO2 beyond alpha!  The first step is being able to run it.  Help with that would be awesome.
