### ISSUE TITLE
[MO2.0.4]VFS not working...

### ISSUE THREAD

**Issue by LeFlemard** [TanninOne/modorganizer#593]
Appologies if someone already found a fix, but I can't seem to make any mod files works right now, the logs point to an error from vfs.. here's the last line of usvfs log :
```
23:13:00.500 [W] windows exception c0000005 from C:\WINDOWS\system32\KERNEL32.DLL
```
And here the complete log of the error:
[usvfs-2016-02-28_22-11-59 - Copie.txt](https://github.com/TanninOne/modorganizer/files/150171/usvfs-2016-02-28_22-11-59.-.Copie.txt)

**Comment by TanninOne** [comment]
How does this point to an error from vfs? It's an exception from a system dll which could be caused by anything, including fallout4 itself or enb or f4se plugin or any external application that hooks into the fo process.
The exception happens after Fallout4 closed anyway so it isn't the cause of FO quitting.

Sorry but this post (and the log) contains nothing that points at the a culprit much less anything I can investigate
