### ISSUE TITLE
Alpha 4: Errors when using "Sort", "Backdate BSAs"

### ISSUE THREAD

**Issue by StormFX** [TanninOne/modorganizer#657]
Whenever I click "Sort"  I get this error:

`21:04:21 [D] [loot] Error: invalid dll, variable loot_game_fo4 not found`

When I use the "Back-date BSAs" option I get this error:

`Windows cannot find C:/Users/<name>/AppData/Local/ModOrganizer/Skyrim\helper.exe`

**Comment by RPINerd** [comment]
Obviously you and I aren't following directions somehow.. I get the same error with trying to sort via LOOT. And if I use the standalone LOOT executable it doesn't recognize the MO modlist. So there must be a way to integrate the two correctly?

**Comment by Still34** [comment]
I'm absolutely frustrated because of this error. I even tried to uninstall MO altogether, and it also deleted all of my mods. (When it asked me whether I want to or not it only gave me an 'ok' option, I had no choice and thought it wasn't going to, glad that I backed up the modlist.txt so I can still grab them again.) 
Even after the re-installation, clean AppData with no MO records, installed with no Fallout4 support, it still gave me this error. Now excuse me I have to grab all the mods again and not use the built-in sorting function.

**Comment by ThosRTanner** [comment]
mod organiser will only delte the mods you installed via mod organiser, as it doesn't keep them in the main games directory. it keeps them somewhere specific to it, and then the VfS makes them visible to the game.

**Comment by Still34** [comment]
I am aware of that, but I thought I was given an option of keeping the personal data (mods, profiles...etc) instead of deleting them outright.

**Comment by TanninOne** [comment]
Both problems should be fixed if using the current MO and loot versions
