### ISSUE TITLE
Will the next version have a working Overwrite dir?

### ISSUE THREAD

**Issue by SadisticLquid** [TanninOne/modorganizer#671]
This is needed for atleast Looksmenu http://www.nexusmods.com/fallout4/mods/12631/? to be able to save character preset

**Comment by Akzyra** [comment]
You can try to create a empty file where presets are normally saved so that it gets overwritten by LooksMenu. 
It wrote the preset into the file, but LooksMenu messed up some ESP names inside the preset and didn't display it ingame. Can't confim if it works, might try later when I fixed up this buggy installation of mine.

**Comment by SadisticLquid** [comment]
Seems it's not working even with the new version

managed to somehow save my preset once meaning there was a file in overwrite but looksmenu load list is empty in game
