### ISSUE TITLE
[Beta 2.0.5] Cannot Launch any External installers

### ISSUE THREAD

**Issue by Leer0x** [TanninOne/modorganizer#719]
Trying to Launch any mod's external installers (After downloading from Nexus to M.O.) leads to error message: installation failed (errorcode 3762504530)
Have tried to download manually and add mod to Mod Organizer...external installers again fails, with same errorcode.

After reinstalling and deleting all Mod Organizer residue, problems still persist.
Restarting PC has no effect.
Turning off Anti-Virus has no effect. 
Running as admin has no effect.

**Comment by Twinki14** [comment]
Getting the same issue.

**Comment by cfs3rd** [comment]
I am also having this issue. When trying to install SkyUI 5.1 same error code. installation failed (errorcode 3762504530) 
My event log:
- System 
  - Provider
   [ Name]  .NET Runtime 
  - EventID 1026 
   [ Qualifiers]  0 
   Level 2 
   Task 0 
   Keywords 0x80000000000000 
  - TimeCreated 
   [ SystemTime]  2016-05-23T15:56:22.620986900Z 
   EventRecordID 27518 
   Channel Application 
   Computer GloriousGaming 
   Security 
- EventData 
   Application: NexusClientCLI.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.TypeLoadException at Nexus.Client.CLI.Program.DoInstall(System.String, System.String, System.String, System.String, System.String, System.Collections.Generic.List`1<System.String>, System.String, System.String ByRef) at Nexus.Client.CLI.Program.Main(System.String[])  

and

- System 
  - Provider
   [ Name]  Application Error 
   - EventID 1000 
   [ Qualifiers]  0 
    Level 2 
    Task 100 
    Keywords 0x80000000000000 
   - TimeCreated 
   [ SystemTime]  2016-05-23T15:56:22.667862000Z 
    EventRecordID 27519 
   Channel Application 
    Computer GloriousGaming 
    Security 
 - EventData 
   NexusClientCLI.exe 
   0.3.0.0 
   572de481 
   KERNELBASE.dll 
   10.0.10586.306 
   571afb9a 
   e0434352 
   000bdae8 
   1404 
   01d1b50ba741f070 
   F:\MO\NCC\NexusClientCLI.exe 
   C:\WINDOWS\SYSTEM32\KERNELBASE.dll 
   37aa0874-026a-45ef-8b95-419e85920464 
    
    Windows 10 Home 64 bit.

**Comment by Geotan00** [comment]
Same problem.

**Comment by TanninOne** [comment]
This should be fixed in 2.0.6b, please test.

**Comment by Geotan00** [comment]
Having a different problem now.

Installation failed: Object reference not set to an instance of an object. [then clicked OK]
Error: installation failed (errorcode 5)

Having this with all the same mods I was trying before.

**Comment by Leer0x** [comment]
@TanninOne Confirming External Installers do work in 2.0.6
Safe to close issue?

**Comment by Leer0x** [comment]
@TanninOne Confirming External installers DO launch. However there are BIG error messages after selecting the install on the external installer...Manager issue or mod installer issue?

**Comment by TanninOne** [comment]
What installer have you been trying and what was the error message(s)?

**Comment by Leer0x** [comment]
NewDialog's
Here are pictures of the 3 error messages I get: http://imgur.com/RJ04vze

**Comment by Leer0x** [comment]
Just tried another External installer, configurable power armor fusion core drain
Error message: http://imgur.com/4NOIEdU

**Comment by TanninOne** [comment]
Please get this file:
https://github.com/TanninOne/modorganizer/releases/download/v2.0.6b/ncc.7z
extract it to your MO folder (this should overwrite several files) and let me know if this fixes the problem.

**Comment by Leer0x** [comment]
Yes! Seems it is fixed! No error messages.
Thank you very much, great to see your work progress!

**Comment by Palpou** [comment]
I had the exact same problem with Mod Organizer when installing the mod "Don't Call Me Settler" (version 1.73)
I took the file ncc.7z and it fixed the problem too.
Thanks TanninOne.
