### ISSUE TITLE
[Beta 2.0.5] Far Harbor DLC showing as unmanaged

### ISSUE THREAD

**Issue by junkajunka** [TanninOne/modorganizer#733]
After installing MO2 standalone into the Fallout 4 directory, when launching it, the main fallout 4 files and all DLC except for Far Harbor are greyed out and not selectable in the right hand pane. Far Harbor is not greyed out and unticked and shows as unmanaged in the left hand pane.

I've renamed the Fallout 4 directory under app data, rerun the launcher and removed and reinstalled MO2 but this has made no difference. 

Game launches ok and I can select (tick) Far Harbor. It also shows as installed in the DLC list in game.

**Comment by sbroadbent** [comment]
I've had this issue, and although I have as yet to jump into the game, I presume as long as it's activated it shouldn't be a problem.

The issue I did have was because DLCCoast.esm is managed by MO, if you forget to activate it, some mods (such as the Armor and Weapon Keywords Community Resource) which check to see which DLCs are active might grey out options during install regarding patches or updates regarding DLC the mod doesn't think you have.

**Comment by junkajunka** [comment]
Thanks, good to know.

Maybe there's a file within MO of official ESMs/ESMS that needs updating for Far Harbor?

**Comment by gerbilOFdoom** [comment]
Line 19 of [this](https://github.com/TanninOne/modorganizer-game_fallout4/blob/master/src/fallout4gameplugins.cpp) needs to be changed to include far harbor

**Comment by junkajunka** [comment]
Cheers.  I'll closed this as it looks like it's down to the beta being out before the DLC.

**Comment by gerbilOFdoom** [comment]
I've submitted a pull request with the change I mentioned earlier. Turns out Github has a fancy feature that lets me edit a file and submit a pull request with the change without ever having to download the repository
