### ISSUE TITLE
Large texture mods (greater than 2GB) cause massive slowdown in loadtime and decreased FPS

### ISSUE THREAD

**Issue by AbstractTheorem** [TanninOne/modorganizer#780]
Created a merged mod from all packages of wasteland 512 (found at http://www.nexusmods.com/fallout4/mods/606/?) the result is a textures directory which is 3.84 GB in size. Using Mod Organizer 2 to manage this directory causes load times from the game to increase, and FPS was cut almost in half at some points.

 Breaking the mod into smaller pieces helped, but removing the mod from mod organizer and installing it manually into the fallout 4 data directory caused all speed issues to disappear.

**Comment by michaelrw10** [comment]
so keep it separate? or group them. Im pretty sure this is just the way it is because MO has to move all of those files into a virtual directory every time you load the game. When they are in the actual datya directory, there is no moving/transferring of files, so obviously its much faster. Perceived speed at launch could also be affected by individual hardware specs. 

Long story short, I remember seeing similar behavior when I used one of those texture optimizer mods for Skyrim where it basically replaced every texture in the game, and this was with MO v1 stable. In fact, what I did with large texture packs like the HighResTexture DLCs (since i unpacked them to optimize with ddsopt), instead of installing them as mods with MO, I installed them directly to the Data directory using wrye bash instead.

**Comment by TanninOne** [comment]
Have you tried reducing the log level? Das that make a difference? You have to restart mo before that change takes effect.

**Comment by AbstractTheorem** [comment]
michaelrw10 - Odd about that happening with Mod Organizer V1. I don't think there is any moving of files... that is the point of using a virtual file system (it is basically all done through things like symbolic links I would imagine). I really don't mind having to manually install large texture mods; I posted this because with the previous versions I had mods running that were multiple GB like that and no slow downs so I thought it might be worth mentioning in case it was a new error.

TanninOne - I dropped logging from "debugging" to "errors" and it reduced the load time a decent amount and removed the FPS issues. The load time is still much slower with the mod enabled through Mod Organizer than installing it manually to the data directory. I thought it was a similar size to the Skyrim and FoNV re-textures I have used with Mod Organizer in the past but this mod is basically 22,127 texture files in a 776 folder directory tree...so it's a bit big (lol). Your program would probably be much happier with me if I made it into a single archive or something!

**Comment by TanninOne** [comment]
Mo2 is still an early beta so it's not exactly performance optimised, correctness comes first. The default setting for logging is set up so i get better error reports, not for "productive" use.

Load time: yes, initial startup will suffer from many files. I may be able to improve on this in the future, but first it has to run bugfree.

**Comment by AbstractTheorem** [comment]
TanninOne - yeah after I realized it was 22,127 files I felt like a bit of an idiot! The load time problems made perfect sense (and are reasonable) -- I thought it had to do with the total file size which made me think it pointed to some other problem since compared to past versions it was acting differently... when in reality it was because I tried to feed it a mod with 22,127 files in it!
