### ISSUE TITLE
Version 2.06b instant CTD in the main menu, Fallout 4 +DLCs 

### ISSUE THREAD

**Issue by GiRaFa-SM** [TanninOne/modorganizer#790]
I've read all suggestions given by members, tried everything, including reinstalling both game and mod Organizer in different folders, nothing worked. 
Anyone has a fix to this problem? Or should I wait for a stable version of MO? NMM messed with my Fallout4 instalation twice and I don't want to back to that crap. If there's no fix.. 

Vanilla game runs perfectly if I run the game through Fallout 4.exe. I disabled almost all my mods and still with the same problem (so it's not a incompatible mod problem..) 

I can provide logs, but can some of you tell me where the files are located? Thank you.

**Comment by SiTWulf** [comment]
Normally a instant crash come from any mod than modidy Strings...

Chek disable any mod than overwrite game strings... for example: Full Dialogue Interface

**Comment by TanninOne** [comment]
The logs are usually under C:\Users\<username>\AppData\Local\ModOrganizer\<instance name>\logs unless you created a portable install, then it's in the logs directory directly inside the mo directory.
But usually game crashes are usually caused by a mod, i.e. a missing master, missing bsa or, as SiTWulf said, a broken game string mod.

**Comment by GiRaFa-SM** [comment]
Like i said, i read all issues related to CTD (starting from #416) when lauching FO4 through mod organizer, tried every solution and tried all you guys suggested again. 

Disabling all mods doesnt work, CTD in SPECIAL Video
Enabling all mod give me CTD in Main Menu
Disabling mods that change game strings doesnt work, CTD in Main Menu.
I installed the same mods that i was using in my past instalation on NMM. 
Its not missing anything, (all dlcs installed) i've checked using Loot and Mod Organizer Plugins screen
You can see in my logs that the mods are installed on another HDD, but i tried with the mods installed in the same HD and i still with this same issue.


[usvfs-2016-06-07_21-13-47 - Copia.txt](https://github.com/TanninOne/modorganizer/files/303758/usvfs-2016-06-07_21-13-47.-.Copia.txt)

**Comment by GiRaFa-SM** [comment]
New log: 
[usvfs-2016-06-08_03-44-51.txt](https://github.com/TanninOne/modorganizer/files/303966/usvfs-2016-06-08_03-44-51.txt)

From what ive seen the last line is: 00:47:18.245 <5532:5168> [W] windows exception c0000005 from C:\Windows\SYSTEM32\MSVCR120.dll

Seems a error in windows files. Not MO itself. Can someone explain me how this has something to do in mod organizer?

**Comment by rdunlap** [comment]
MSVCR120.dll is Microsoft Visual C Runtime and is what ModOrganizer and most windows programs are built on one version of this or another.

**Comment by rdunlap** [comment]
It sounds like a mod problem. If it were me i would make a backup of the plugins list and then disable the top half and run the game. If it runs you know that the problem is in the disabled half. Then do the other half. once you isolate which half then do the same thing with the problem half until you have it narrowed down. Full Dialog did that to me before he updated it and i had to hunt it down.

robert

**Comment by GiRaFa-SM** [comment]
Lol, read again please. I disabled all my mods (read all plugins) and I still with the same problem. 

If you want I can even record a video.

**Comment by rdunlap** [comment]
sorry i was unclear. Are you disabling in the right pane or left? I said plugin *(right pane) when I should have said Mod *(left pane) most of the problem mods i have come across the actual problem turned out to be in loose files and to stop them from loading you have to disable the whole mod or the problems themselves are still loading. 

NMM install should not be a problem. I keep it installed so if a mod user of mine has an issue I can try to reproduce it and help them. It has never caused a problem for me.

robert

**Comment by GiRaFa-SM** [comment]
I'm disabling all mods, when I do this the plugins in the tight panel disappear, and I assume that I disabled all active plugins. 

The game only crashes if I try to run it through Mod Organizer.

**Comment by GiRaFa-SM** [comment]
Just adding more info. 

When I installed Mod Organizer I tested with 1 mod to check how it works, Fallout 4 at first was running without problems with only this mod, then I started installed my personal mods and tried to manage profiles. 
(at this point i didn't tested running fallout 4 with all my mods enabled through MO) 

I don't know if this issue was already quoted, but I have FC  when I try to manage different profiles, I clicked twice in Default Profile to manage my saves and see saves from only one user. No FC, just a strange issue.

**Comment by pantera160** [comment]
Are you running it with F4SE? What type of MO are you using, the portabled
of not? Could you try to install an other MO and run FO4 using this one
without adding any mod.

2016-06-08 16:52 GMT+02:00 GiRaFa-SM <notifications@github.com>:

**Comment by GiRaFa-SM** [comment]
I'm not using F4SE(a utilly for scrips isnt it?). Im not using the portable version. 
You mean another profile? If i do this, can you explain me how i could move my installed mods to the new instalation( just moving folders, in this case, mod folder?) 

Adding more info above: Most of my mods are already converted to ba2. So is very hard to have texture conflitcts.

**Comment by michaelrw10** [comment]
I would: 

- completely uninstall every mod from MO2 (keep the downloaded installation files so it is easy to reinstall them later)
- uninstall MO2 (preferably using the windows uninstaller)
- delete all MO2 settings files (i.e. delete the entire ModOrganizer directory at **%localappdata%\ModOrganizer**)
- completely uninstall Nexus Mod Manager (if you have it installed)
- Delete all NMM settings folders in %localappdata% (if it was previously installed)
- Delete any of the NMM VirtualInstall folders (if it was previously installed) (location of VirtualInstall folders depends on your NMM settings) 
- Completely uninstall FO4 (backup your INIs, saves, anything else important)
- Make sure that your Fallout 4 directory is completely empty/removed (located at **<PATH>\Steam\steamapps\common\Fallout 4\**)
- restart your machine
- reinstall FO4, start it up and make sure it works
- reinstall MO2, set all of your settings, then run FO4 to confirm it works
- slowly work through reinstalling all mods, and frequently start FO4 to make sure its still functioning (don't wait until youve installed 200 mods before testing FO4 again.. you want to try to identify if there is a mod that's causing the problem, so test frequently.. only a few mods at a time)

**Comment by GiRaFa-SM** [comment]
I manage Witcher 3 through NMM, but ill try that again. I did 90% of what you said and no luck, i'll try again.

**Comment by scotty9090** [comment]
Is your overwrite folder empty or are there files in there?  I had a similar behavior after FO4Edit dumped some files in my overwrite folder.  As soon as I removed the files I was good again.  Note that it seemed to be the presence of *any* file, not just things that were actually loaded by the game.

**Comment by GiRaFa-SM** [comment]
Empty overwrite folder.

**Comment by GiRaFa-SM** [comment]
I'm already having headaches with this, i think i've reinstalled this game 5x because of NCrapManager.

**Comment by michaelrw10** [comment]
hmm..
there was a point back in December or January where I was having similar problems (at the time, we were running MO2 alpha) ... i never identified what the cause was.. but i fixed my problems by completely uninstalling everything.. all managers, all mods, and FO4 itself. deleting all associated files/folders/settings in AppData, running Ccleaner registry to remove empty keys, ... the whole nine yards.. 
After slowly and deliberately reinstalling, my problem was resolved. To this day, I have no idea what the problem was.

**Comment by GiRaFa-SM** [comment]
I Solved the problem. It was a mod called BetterArmorNamingAndSorting by rudy88. Tested mod by mod, reorganized my mod-loadorder and found the problem. Thanks everyone specialy michal for suggesting unistall one by one and opening the game, sure it was a headache.
