### ISSUE TITLE
Repeated error "87" when launching any external applications

### ISSUE THREAD

**Issue by alex-eyre** [TanninOne/modorganizer#895]
Hello!
I have tried running mod organizer in every single compatibility mode, with and without admin rights (including no compatibility mode).
However I believe the problem lies with Windows 10, or so it seems is the only variable that I haven't changed in an attempt to fix it.
Any fixes avaliable for this?

Specs:
- AMD FX 8320
- GTX 780
- 8Gb RAM
- ModOrganizer version 2.0.7
- Windows 10 Build 14393

If you want any more information then don't hesistate to ask!

**Comment by NegZed** [comment]
I moved it out MO out of my program files, as well as turned off any admin requirements on my PC, and I don't get that issue anymore. Maybe just try to install MO on your C Drive. If you want to keep it in their you are either going to have to open it as admin every time, or go into your registries and turn off admin requirements. Search the latter up on google if you are doing that because I can't remember how.
